### ISSUE TITLE
FREE STATE Education pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#10]
- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/FREE%20STATE%20EDUCATION.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by NicolaasJKotze** [comment]
Hi. May I do this one please?

**Comment by schalkventer** [comment]
Go for it!

**Comment by jbothma** [comment]
Thanks!

**Comment by jbothma** [comment]
This is now available at https://keepthereceipts.org.za/?implementation_location_province=Free+State&buyer_name=Free+State+Department+of+Education
