### ISSUE TITLE
Department of Tourism (DT) -  pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#100]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/TOURISM%20and%20SA%20TOURISM%20-%20COVID%20SPEND.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201202203625/http://ocpo.treasury.gov.za/COVID19/Documents/TOURISM%20and%20SA%20TOURISM%20-%20COVID%20SPEND.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by nefiger** [comment]
can I grab this?

**Comment by nefiger** [comment]
@schalkventer http://ocpo.treasury.gov.za/COVID19/Documents/TOURISM%20and%20SA%20TOURISM%20-%20COVID%20SPEND.pdf - no text found, this is an image file

**Comment by schalkventer** [comment]
Thanks for the heads up @nefiger. @jbothma is this where we whip out the OCR flow?

**Comment by tristynferreiro** [comment]
Uploaded last table

**Comment by tristynferreiro** [comment]
Uploaded
