### ISSUE TITLE
Department of Trade, Industry and Competition (the DTIC) -  pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#101]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/TRADE%2cINDUSTRY%20AND%20COMPETITION%20AND%20ENTITIES%20-%20PPE%20Annex.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by sacheen** [comment]
could i take this one?

**Comment by jbothma** [comment]
please do!

**Comment by sacheen** [comment]
For these big files with various tables, do i submit a pull request for each table? or how does one submit multiple files in one PR?

**Comment by tristynferreiro** [comment]
Uploaded pages 1-3

**Comment by tristynferreiro** [comment]
Uploaded buyer 4

**Comment by tristynferreiro** [comment]
Uploaded buyer 10

**Comment by tristynferreiro** [comment]
Uploaded buyer 11

**Comment by tristynferreiro** [comment]
Uploaded buyer 12

**Comment by tristynferreiro** [comment]
Uploaded buyer 14

**Comment by tristynferreiro** [comment]
uploaded buyer 16

**Comment by tristynferreiro** [comment]
Uploaded buyers 1,2,3,6,8,9,13,15,17

**Comment by tristynferreiro** [comment]
Buyers 18 and 5 didn't have tables to extract
