### ISSUE TITLE
Department of Basic Education (DBE) -  pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#103]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/BASIC%20EDUCATION%20-%20Covid19%20Expenditure.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201107181631/http://ocpo.treasury.gov.za/COVID19/Documents/BASIC%20EDUCATION%20-%20Covid19%20Expenditure.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by sacheen** [comment]
could i take this one?

**Comment by jbothma** [comment]
please do!

**Comment by tristynferreiro** [comment]
Uploaded!
