### ISSUE TITLE
Department of Health (DoH) -  pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#104]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/HEALTH%20PPE%20.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201106205700/http://ocpo.treasury.gov.za/COVID19/Documents/HEALTH%20PPE%20.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by sacheen** [comment]
could i take this one?

**Comment by jbothma** [comment]
please do!

**Comment by jbothma** [comment]
Thanks!

Please make sure everything that's one row in the table in the PDF is one row in the CSV.

![Screenshot_2020-10-03_11-32-31](https://user-images.githubusercontent.com/235801/94988257-393f7900-056c-11eb-8c4a-0d7f049f703c.png)
![Screenshot_2020-10-03_11-32-16](https://user-images.githubusercontent.com/235801/94988260-3b093c80-056c-11eb-9587-0b7e2494a999.png)

See how it's all one row here (ignore the fact that `name of entity` and `total amount` should be different columns, that's a different issue.

![Uploading Screenshot_2020-10-03_11-34-15.png…]()

**Comment by jbothma** [comment]
Watch out - the `Name of entity` and `Total amount` columns have been merged - they need to be split
![Screenshot_2020-10-03_11-38-55](https://user-images.githubusercontent.com/235801/94988381-08ac0f00-056d-11eb-8592-ad976c0b72fd.png)

![Screenshot_2020-10-03_11-37-16](https://user-images.githubusercontent.com/235801/94988372-ec0fd700-056c-11eb-8929-24508b913b2f.png)

**Comment by tristynferreiro** [comment]
Uploaded
