### ISSUE TITLE
Department of Higher Education and Training (DHET) -  pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#105]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/HIGHER%20EDUCATION%20AND%20TRAINING%20and%20NAT%20SKILLS%20FUND%20-%20COVID-19%20PROCUREMENTS.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201105094115/http://ocpo.treasury.gov.za/COVID19/Documents/HIGHER%20EDUCATION%20AND%20TRAINING%20and%20NAT%20SKILLS%20FUND%20-%20COVID-19%20PROCUREMENTS.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by sacheen** [comment]
could i take this one?

**Comment by jbothma** [comment]
please do!

**Comment by tristynferreiro** [comment]
Uploaded
