### ISSUE TITLE
Department of Social Development (DSD) -  pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#106]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/SOCIAL%20DEVELOPMENT%20-%20COVID%20LIST.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201112233159/http://ocpo.treasury.gov.za/COVID19/Documents/SOCIAL%20DEVELOPMENT%20-%20COVID%20LIST.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by sacheen** [comment]
I'd like to try this. can I have this one?

**Comment by jbothma** [comment]
Go for it! Thanks!

**Comment by tristynferreiro** [comment]
Uploaded
