### ISSUE TITLE
Department of Social Development (DSD) - National Development Agency (NDA) pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#107]
Public Entity

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/NATIONAL%20DEVELOPMENT%20AGENCY%20%20-COVID-19.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201128043228/http://ocpo.treasury.gov.za/COVID19/Documents/NATIONAL%20DEVELOPMENT%20AGENCY%20%20-COVID-19.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by Lean3Viljoen94** [comment]
And this one :)

**Comment by schalkventer** [comment]
👍

**Comment by Lean3Viljoen94** [comment]
I might not get to this one today, my SASSA file is massive. Unassigning myself incase someone else can pick it up

**Comment by schalkneethling** [comment]
@schalkventer I can grab this one

**Comment by tristynferreiro** [comment]
Uploaded both
