### ISSUE TITLE
Department of Social Development (DSD) - South African Social Security Agency (SASSA) pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#108]
Public Entity

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/SASSA%20-%20Covid%2019%20Procurement%20March%202020%20-%20Head%20Office%20and%20Regions%20PPE%20only.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201108113643/http://ocpo.treasury.gov.za/COVID19/Documents/SASSA%20-%20Covid%2019%20Procurement%20March%202020%20-%20Head%20Office%20and%20Regions%20PPE%20only.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by Lean3Viljoen94** [comment]
Hi, mind if I pick up this one?

**Comment by schalkventer** [comment]
Yup!

**Comment by Chantevdw** [comment]
Reviewing

**Comment by tristynferreiro** [comment]
I fixed the issues in the EC and KZN tables and merged

**Comment by tristynferreiro** [comment]
The above three PRs are the three missing tables. I have extracted all three of them.

**Comment by tristynferreiro** [comment]
Uploaded GP to keepthereciepts

**Comment by tristynferreiro** [comment]
Uploaded Table 2 (standard orders)

**Comment by tristynferreiro** [comment]
Uploaded NW table

**Comment by tristynferreiro** [comment]
Uploaded table 4

**Comment by tristynferreiro** [comment]
Uploaded KZN table

**Comment by candidcreature** [comment]
Uploaded FS

**Comment by tristynferreiro** [comment]
Uploaded FS

**Comment by tristynferreiro** [comment]
Uploaded HO

**Comment by tristynferreiro** [comment]
Uploaded WC

**Comment by tristynferreiro** [comment]
Uploaded NC

**Comment by tristynferreiro** [comment]
Uploaded EC

**Comment by tristynferreiro** [comment]
All uploaded :D!
