### ISSUE TITLE
Department of Sports, Arts and Culture (DSAC) -  pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#109]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/SPORT%2c%20ARTS%20AND%20CULTURE%20-%20Procument%20During%20Covid19%20Pandemic.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by Lean3Viljoen94** [comment]
And this one

**Comment by schalkventer** [comment]
Go for it!

**Comment by Lean3Viljoen94** [comment]
This one is image-based as well 🙃

**Comment by Lean3Viljoen94** [comment]
Might not get to this one today, unassigning myself incase someone else can pick it up

**Comment by martink-rsa** [comment]
I'll take it.

**Comment by schalkventer** [comment]
Assigned to you now @martink-rsa

**Comment by martink-rsa** [comment]
https://github.com/South-Africa-Government-Procurement/Data-cleaning/pull/186

**Comment by Chantevdw** [comment]
reviewing
