### ISSUE TITLE
FREE STATE Health pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#11]
- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/FREE%20STATE%20HEALTH.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201024162449/http://ocpo.treasury.gov.za/COVID19/Documents/FREE%20STATE%20HEALTH.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by JasonTame** [comment]
@jbothma I'm happy to take this one on

**Comment by jbothma** [comment]
Thanks!

**Comment by jbothma** [comment]
This is an interesting case - looks like we should clarify the documentation (I probably didn't pay attention properly if you asked):

- We don't want total rows
- We do want total columns - the Free State often provide this breakdown of committed (order_amount_zar) and paid/unpaid split. We want the total in this case.

Do you mind including the final column after all?

![Screenshot_2020-10-18_13-58-31](https://user-images.githubusercontent.com/235801/96366748-055a7b00-114a-11eb-8e89-20f01f22bd16.png)

**Comment by jbothma** [comment]
Looks like the last row is shifted to the left - could you fix that?

![Screenshot_2020-10-18_14-11-19](https://user-images.githubusercontent.com/235801/96367073-efe65080-114b-11eb-9daf-671f89959861.png)

**Comment by jbothma** [comment]
In this case the item description needs to be filled down.

We need a row for each unique

- supplier
- order amount
- buyer
- order number (this is often not provided but we wouldn't merge the same supplier coming up twice in a table into one row - distinct rows imply distinct orders)

![Screenshot_2020-10-18_14-18-53](https://user-images.githubusercontent.com/235801/96367236-dc87b500-114c-11eb-9f29-72ab1c7c04bf.png)
![Screenshot_2020-10-18_14-18-40](https://user-images.githubusercontent.com/235801/96367237-ddb8e200-114c-11eb-919d-3e0b2039ac4d.png)

**Comment by jbothma** [comment]
Looks like the quantity column in one table aligned with a cost column in another table

![Screenshot_2020-10-18_14-30-45](https://user-images.githubusercontent.com/235801/96367510-93d0fb80-114e-11eb-814c-e51d67536886.png)
![Screenshot_2020-10-18_14-30-34](https://user-images.githubusercontent.com/235801/96367511-959abf00-114e-11eb-916e-52a99f20e00f.png)

**Comment by jbothma** [comment]
I wonder if each table is a hospital. But I don't see headings suggesting that.

Would be cool to ask them.

**Comment by jbothma** [comment]
missed the last row of the last table but I'll add it

**Comment by jbothma** [comment]
Started uploading this

**Comment by jbothma** [comment]
Done the first file but distracted by bugs and adding a couple of new fields for this dataset in the backend. The first file is available at https://keepthereceipts.org.za/?implementation_location_province=Free+State&buyer_name=Free+State+Department+of+Health so long.

**Comment by tristynferreiro** [comment]
Uploaded table 2

**Comment by tristynferreiro** [comment]
Uploaded table 3

**Comment by tristynferreiro** [comment]
uploaded table 4

**Comment by tristynferreiro** [comment]
uploaded table 5

**Comment by tristynferreiro** [comment]
uploaded table 6

**Comment by tristynferreiro** [comment]
uploaded table 7
