### ISSUE TITLE
FREE STATE Human Settlements pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#12]
- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/FREE%20STATE%20HUMAN%20SETTLEMENTS.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201113011605/http://ocpo.treasury.gov.za/COVID19/Documents/FREE%20STATE%20HUMAN%20SETTLEMENTS.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by enemkaywun** [comment]
hi please assign this to me

**Comment by schalkventer** [comment]
All yours @enemkaywun

**Comment by jbothma** [comment]
Thanks!

**Comment by tristynferreiro** [comment]
Uploaded
