### ISSUE TITLE
FREE STATE Office of the Premier pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#13]
- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/FREE%20STATE%20OFFICE%20OF%20THE%20PREMIER.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by NarothamSai** [comment]
Hi, can I work on this?

**Comment by schalkventer** [comment]
Go for it @NarothamSai !

**Comment by jbothma** [comment]
Thanks! This is now available at https://keepthereceipts.org.za/?implementation_location_province=Free+State&buyer_name=Free+State+Office+of+the+Premier
