### ISSUE TITLE
FREE STATE Police, Roads and Transport pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#14]
- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/FREE%20STATE%20POLICE%2c%20ROADS%20and%20TRANSPORT.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by NarothamSai** [comment]
Hi, can I work on this one?

**Comment by jbothma** [comment]
Please do! Thanks!

**Comment by jbothma** [comment]
Thanks! This is now at https://keepthereceipts.org.za/?implementation_location_province=Free+State&buyer_name=Free+State+Department+of+Police%2C+Roads+and+Transport
