### ISSUE TITLE
FREE STATE Provincial Treasury Tender Bulletin 2 - pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#16]
- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/FREE%20STATE%20FINANCE%20TENDER%20BULLETIN%20-%202.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by zacharlie** [comment]
I can do this one, but I have a couple of quick questions...

You guys mention that [multiple tables with the same column structure can be merged](https://github.com/South-Africa-Government-Procurement/Data-cleaning#should-we-put-different-tables-into-different-csvs) but don't indicate whether to insert a new column for the table name (in this case, the Tender ID).

I feel like that's introducing data loss and instructions should rather be added to the readme, along with a standard naming convention when using multiple tables.

**Comment by jbothma** [comment]
That's exactly what we'd like people to do (without the data loss!)

We would like people to add a column to distinguish the rows from tables in different section headings.

Would you mind adding that ot the README? https://github.com/South-Africa-Government-Procurement/Data-cleaning

**Comment by jbothma** [comment]
reviewing

**Comment by jbothma** [comment]
Thanks! This is now live at https://keepthereceipts.org.za/

**Comment by jbothma** [comment]
visually seems to be the same data as #15 just  republish of the same tender bulletin
