### ISSUE TITLE
FREE STATE Public Works and Infrastructure pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#17]
- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/FREE%20STATE%20PUBLIC%20WORKS%20INFRASTRUCTURE.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201018180544/http://ocpo.treasury.gov.za/COVID19/Documents/FREE%20STATE%20PUBLIC%20WORKS%20INFRASTRUCTURE.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by BiancaOliver** [comment]
hey, can I take this one?

**Comment by schalkventer** [comment]
@BiancaOliver go for it!

**Comment by jbothma** [comment]
Thanks!

**Comment by jbothma** [comment]
@BiancaOliver would you by any chance have time and be interested in formatting this like https://github.com/keep-the-receipts/data-extraction/blob/d7c78d558161fadf1d24d8519a248892c1d9dfcc/Provincial%20Government/Free%20State/Public%20Works%20and%20Infrastructure/STATE-OWNED%20RESORTS%20REFURBISHED.csv ?

This involves

- splitting each distinct table out to its own file
- formatting ZAR amounts like 123.45 without spaces, thousand sepators or R
- renaming columns according to https://github.com/keep-the-receipts/project-docs/wiki/Data-models-and-standards#column-names
- Adding a buyer_name and implementation_location_province column

I know it's short notice so no stress if you don't have time - I'd like to get it done before Tuesday - so just let me know if you're keen, otherwise I'll finish it up tomorrow.

**Comment by jbothma** [comment]
The first file is available at https://keepthereceipts.org.za/?implementation_location_province=Free+State&buyer_name=Free+State+Department+of+Public+Works

**Comment by tristynferreiro** [comment]
Uploaded disinfection table

**Comment by tristynferreiro** [comment]
Uploaded privately owned sites and expenditure

**Comment by tristynferreiro** [comment]
Uploaded construction of field hospital table

**Comment by tristynferreiro** [comment]
Uploaded security companies appointed table
