### ISSUE TITLE
FREE STATE Sport, Arts, Culture and Recreation pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#19]
- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/FREE%20STATE%20SPORTS%2c%20ARTS%2c%20CULTURE%20AND%20RECREATION.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by NarothamSai** [comment]
Hi, Can I work on this one?

**Comment by jbothma** [comment]
Thanks! This is now available at https://keepthereceipts.org.za/?implementation_location_province=Free+State&buyer_name=Free+State+Department+of+Sports%2C+Arts%2C+Culture+and+Recreation
