### ISSUE TITLE
GAUTENG  pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#20]
- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/GAUTENG%20PROVINCIAL%20GOVERNMENT.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by schalkneethling** [comment]
I can grab this one @jbothma

**Comment by tristynferreiro** [comment]
uploaded provincial treasury

**Comment by tristynferreiro** [comment]
uploaded Gauteng Department of Agriculture and Rural Development

**Comment by tristynferreiro** [comment]
Uploaded CoGTA

**Comment by tristynferreiro** [comment]
Uploaded eGovernment

**Comment by tristynferreiro** [comment]
Uploaded gfleet

**Comment by tristynferreiro** [comment]
Uploaded Department of Soc Dev

**Comment by tristynferreiro** [comment]
Uploaded Department of Soc Dev transversal

**Comment by tristynferreiro** [comment]
uploaded ppe procured through DOH

**Comment by tristynferreiro** [comment]
uploaded economic development

**Comment by tristynferreiro** [comment]
uploaded GIFA

**Comment by tristynferreiro** [comment]
uploaded GMA

**Comment by tristynferreiro** [comment]
uploaded DOH ppe

**Comment by tristynferreiro** [comment]
uploaded DOH without pos

**Comment by tristynferreiro** [comment]
Uploaded DOH medical equipment

**Comment by tristynferreiro** [comment]
Uploaded other and infrastructure

**Comment by tristynferreiro** [comment]
uploaded community safety

**Comment by tristynferreiro** [comment]
uploaded DOE

**Comment by tristynferreiro** [comment]
Uploaded premier
