### ISSUE TITLE
GAUTENG Human Settlements pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#21]
- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/GAUTENG%20HUMAN%20SETTLEMENTS%20Procurement%20for%20COVID-19%20Report.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by schalkneethling** [comment]
I can grab `pass 1` @jbothma

**Comment by schalkventer** [comment]
Go for it @schalkneethling!

**Comment by tristynferreiro** [comment]
Uploaded
