### ISSUE TITLE
EASTERN CAPE  pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#22]
- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/EASTERN%20CAPE%20PROVINCIAL%20GOVERNMENT%20-%20Covid19%20list%20of%20suppliers.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201208202809/http://ocpo.treasury.gov.za/COVID19/Documents/EASTERN%20CAPE%20PROVINCIAL%20GOVERNMENT%20-%20Covid19%20list%20of%20suppliers.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by carlvdm** [comment]
Can I grab this one?

There are 2 tables, do you want them uploaded separately?

![Screenshot from 2020-10-03 15-14-32](https://user-images.githubusercontent.com/25169028/94992573-3f911d80-058b-11eb-9781-09ab554a9444.png)
![Screenshot from 2020-10-03 15-14-34](https://user-images.githubusercontent.com/25169028/94992575-41f37780-058b-11eb-86d2-196c7f1b807a.png)

**Comment by carlvdm** [comment]
https://github.com/South-Africa-Government-Procurement/Data-cleaning/pull/222 :slightly_smiling_face:

**Comment by jbothma** [comment]
These are the tables we need


![Screenshot_2020-12-07_15-14-23](https://user-images.githubusercontent.com/235801/101355272-02088380-389f-11eb-894a-99d081e42b12.png)
![Screenshot_2020-12-07_15-14-04](https://user-images.githubusercontent.com/235801/101355275-0339b080-389f-11eb-86b8-8edcc5feae06.png)



![Screenshot_2020-12-07_15-14-54](https://user-images.githubusercontent.com/235801/101355257-ff0d9300-389e-11eb-8fbd-68c06ae81448.png)

**Comment by tristynferreiro** [comment]
Uploaded DOH tables

**Comment by tristynferreiro** [comment]
Uploaded tables starting pg 42

**Comment by tristynferreiro** [comment]
Uploaded tables starting pg 6

**Comment by tristynferreiro** [comment]
Uploaded supplier list tables
