### ISSUE TITLE
WESTERN CAPE  pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#23]
- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/Western%20Cape%20Government%20-%20Covid-19%20Reporting%20Presidency%20verified%20info.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by NicolaasJKotze** [comment]
I will do this one.

**Comment by jbothma** [comment]
[Western Cape Government - Covid-19 Reporting Presidency verified info-OCRd.pdf](https://github.com/South-Africa-Government-Procurement/Data-cleaning/files/5321811/Western.Cape.Government.-.Covid-19.Reporting.Presidency.verified.info-OCRd.pdf)

**Comment by tristynferreiro** [comment]
Uploaded
