### ISSUE TITLE
LIMPOPO Supplier Directors March to June pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#26]
- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/LIMPOPO%20GOVERNMENT%20-%20SUPPLIER%20DIRECTORS%20-%20COVID-19%20-%20March%202020%20to%20June%202020.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201203104320/http://ocpo.treasury.gov.za/COVID19/Documents/LIMPOPO%20GOVERNMENT%20-%20SUPPLIER%20DIRECTORS%20-%20COVID-19%20-%20March%202020%20to%20June%202020.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by MarlaWillemse** [comment]
May I do this one?

**Comment by MarlaWillemse** [comment]
There's no purchase data in this one.

**Comment by tristynferreiro** [comment]
Uploaded
