### ISSUE TITLE
NORTHERN CAPE  pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#27]
- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/Northern%20Cape%20COVID-19%20expenditure%20report%20April%20-%20July%202020%20.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201208195926/http://ocpo.treasury.gov.za/COVID19/Documents/Northern%20Cape%20COVID-19%20expenditure%20report%20April%20-%20July%202020%20.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by JesseVermeulen123** [comment]
Hey, could I please do this one?

**Comment by jbothma** [comment]
Hi!

National departments and the Free State are higher priority, but if you'd
prefer this one, that'd also be helpful - go ahead :) Thanks!

JD

**Comment by tristynferreiro** [comment]
Uploaded
