### ISSUE TITLE
FREE STATE Education pass 2

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#28]
- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/FREE%20STATE%20EDUCATION.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201018180029/http://ocpo.treasury.gov.za/COVID19/Documents/FREE%20STATE%20EDUCATION.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by CamGreen** [comment]
Hi, can you please assign me to this issue? Thanks.
