### ISSUE TITLE
Examplars for volunteers

### ISSUE THREAD

**Issue by vukosim** [keep-the-receipts/data-extraction#3]
Could we create an examplar for a full process of what we would want as a perfect output?

Then we can write a guide for others to assist. 

@jbothma

**Comment by jbothma** [comment]
Yep, I'll do a couple of examples tonight at Codebridge Community Evening

**Comment by jbothma** [comment]
https://join.keepthereceipt.org.za/

**Comment by vukosim** [comment]
Looks great @jbothma
