### ISSUE TITLE
FREE STATE Human Settlements pass 2

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#30]
- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/FREE%20STATE%20HUMAN%20SETTLEMENTS.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by CamGreen** [comment]
Hi, Can you please assign me to this issue, thanks.

**Comment by schalkventer** [comment]
Go for it @CamGreen!
