### ISSUE TITLE
FREE STATE Social Development pass 2

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#36]
- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/FREE%20STATE%20SOCIAL%20DEVELOPMENT.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by JasonTame** [comment]
@jbothma I'm happy to take this one on

**Comment by jbothma** [comment]
Thanks!

**Comment by jbothma** [comment]
Brilliant!
