### ISSUE TITLE
FREE STATE Sport, Arts, Culture and Recreation pass 2

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#37]
- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/FREE%20STATE%20SPORTS%2c%20ARTS%2c%20CULTURE%20AND%20RECREATION.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by CamGreen** [comment]
Hi, Can you please assign me to this issue, thanks.
