### ISSUE TITLE
KWAZULU-NATAL  pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#42]
- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/KZN%20PROVINCIAL%20GOVERNMENT%20-%20Procurement%20Disclosure.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201208202526/http://ocpo.treasury.gov.za/COVID19/Documents/KZN%20PROVINCIAL%20GOVERNMENT%20-%20Procurement%20Disclosure.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by JasonTame** [comment]
Hey @jbothma Can I take this one on?

**Comment by jbothma** [comment]
Yeah please do! Thanks!

**Comment by JasonTame** [comment]
Thanks! Working on it now. Not a straightforward process, had to first OCR it and then export each table to CSV and fix the formatting, tabula keeps splitting words into separate columns. Will tackle it when I have gaps throughout the weekend :)

**Comment by tristynferreiro** [comment]
Uploaded

**Comment by tristynferreiro** [comment]
Uploaded Infrastructure

**Comment by tristynferreiro** [comment]
Uploaded expenditure per provincial department
