### ISSUE TITLE
National Assembly (NA) - Public Service Commission (PSC) pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#46]
Constitutional Body

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/PUBLIC%20SERVICE%20COMMISSION%20-%20LIST%20OF%20PROCURED%20GOODS%20OR%20SERVICES%20TO%20FIGHT%20THE%20SPREAD%20COVID19.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by carlvdm** [comment]
May I grab this one? :)

**Comment by carlvdm** [comment]
https://github.com/South-Africa-Government-Procurement/Data-cleaning/pull/197 :slightly_smiling_face:

**Comment by tristynferreiro** [comment]
Uploaded! *pops the champagne*
