### ISSUE TITLE
The Presidency -  pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#47]
Presidency

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/PRESIDENCY%20-%20REPORT%20TO%20THE%20IMC%20-%20RFI-Breakdown%20PPEs%20Expenditure%2012%20AUG%202020.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201213003740/http://ocpo.treasury.gov.za/COVID19/Documents/PRESIDENCY%20-%20REPORT%20TO%20THE%20IMC%20-%20RFI-Breakdown%20PPEs%20Expenditure%2012%20AUG%202020.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by JonathanAspeling** [comment]
I'm keen to take this one @jbothma

**Comment by jbothma** [comment]
Awesome! Go for it!

**Comment by JonathanAspeling** [comment]
Cool Ready to do a PR - but think the issue first has to be assigned to me @jbothma ? :)

**Comment by JonathanAspeling** [comment]
![image](https://user-images.githubusercontent.com/42679894/94142930-4d4df100-fe6f-11ea-9b93-8c99861bdb69.png)

**Comment by JonathanAspeling** [comment]
I've taken the two tables and ran them through Tabula :D

The one came out very nice the other not so much - so I tried formatting it into a contiguous table.


[(JonathanFormatVersion) PPE PROCUREMENT - PRESIDENCY - REPORT TO THE IMC - RFI-Breakdown PPEs Expenditure 12 AUG 2020.zip](https://github.com/South-Africa-Government-Procurement/Data-cleaning/files/5275839/JonathanFormatVersion.PPE.PROCUREMENT.-.PRESIDENCY.-.REPORT.TO.THE.IMC.-.RFI-Breakdown.PPEs.Expenditure.12.AUG.2020.zip)

**Comment by schalkventer** [comment]
Ah, I might need to update the video to deal with this. Thanks for point this out @JonathanAspeling

**Comment by tristynferreiro** [comment]
Uploaded
