### ISSUE TITLE
The Presidency - Department of Planning, Monitoring and Evaluation (DPME) pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#48]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/PLANNING%20MONITORING%20and%20EVALUATION%20-%20Covid%20-19%20Expenditure.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by carlvdm** [comment]
May I grab this one? :slightly_smiling_face:

**Comment by carlvdm** [comment]
Do you want us to remove these top rows?
![Screenshot from 2020-10-03 14-11-09](https://user-images.githubusercontent.com/25169028/94991397-3734e480-0583-11eb-800a-acda6d24fce7.png)

**Comment by carlvdm** [comment]
https://github.com/South-Africa-Government-Procurement/Data-cleaning/pull/190 :slightly_smiling_face:

**Comment by tristynferreiro** [comment]
Uploaded
