### ISSUE TITLE
The Presidency - Department of Women, Youth and Persons with Disabilities (DWYPD) pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#49]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/WOMEN%20YOUTH%20AND%20PERSONS%20WITH%20DISABILITY%20-%20REPORT%20ON%20COVID%2019%20SPENT%2007082020.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201106203008/http://ocpo.treasury.gov.za/COVID19/Documents/WOMEN%20YOUTH%20AND%20PERSONS%20WITH%20DISABILITY%20-%20REPORT%20ON%20COVID%2019%20SPENT%2007082020.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by Chantevdw** [comment]
Can I do this one

**Comment by Chantevdw** [comment]
I get this error from Tabula:
![image](https://user-images.githubusercontent.com/20510657/94991991-0b1b6280-0587-11eb-9fbe-e3b0cab4a598.png)

**Comment by jbothma** [comment]
Does this help you?

https://github.com/South-Africa-Government-Procurement/Data-cleaning/blob/master/README.md#tabula-gives-me-the-following-error-for-the-pdf-sorry-your-pdf-file-is-image-based-it-does-not-have-any-embedded-text-it-might-have-been-scanned-from-paper-tabula-isnt-able-to-extract-any-data-from-image-based-pdfs-click-the-help-button-for-more-information

**Comment by jbothma** [comment]
[WOMEN YOUTH AND PERSONS WITH DISABILITY - REPORT ON COVID 19 SPENT 07082020-OCRd.pdf](https://github.com/South-Africa-Government-Procurement/Data-cleaning/files/5321667/WOMEN.YOUTH.AND.PERSONS.WITH.DISABILITY.-.REPORT.ON.COVID.19.SPENT.07082020-OCRd.pdf)

**Comment by Chantevdw** [comment]
Thanks @jbothma 

The data when exported is quite messed up.

![image](https://user-images.githubusercontent.com/20510657/94994466-0317ee80-0598-11eb-898b-3dc6dc53f82e.png)

**Comment by tristynferreiro** [comment]
Uploaded!
