### ISSUE TITLE
The Presidency - Government Communication and Information System (GCIS) pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#50]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/GCIS%20-%20REPORT%20on%20COVID%20Expenditure.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201126013442/http://ocpo.treasury.gov.za/COVID19/Documents/GCIS%20-%20REPORT%20on%20COVID%20Expenditure.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by carlvdm** [comment]
Ah this one is image-based and Tabula won't be able to read it:

![Screenshot from 2020-10-03 14-06-25](https://user-images.githubusercontent.com/25169028/94991197-bf19ef00-0581-11eb-93cf-9b2cfd4cd9d3.png)

**Comment by tristynferreiro** [comment]
Uploaded table 1/3

**Comment by tristynferreiro** [comment]
Uploaded 2/3

**Comment by tristynferreiro** [comment]
uploaded 3/3
