### ISSUE TITLE
The Presidency - Statistics South Africa (Stats SA) pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#51]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/STATS%20SA%20-%20Annexure%20A%20-%20Covid%2010%20Related%20Activities%20Procurement%2031%20July%202020.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by douglas86** [comment]
hey, can i take this one.

**Comment by tristynferreiro** [comment]
Uploaded!
