### ISSUE TITLE
The Presidency - Statistics South Africa (Stats SA) pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#52]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/STATS%20SA%20-%20Annexure%20B%20-%20Covid%2010%20PPE%20Procurement%2031%20July%202020.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201105085646/http://ocpo.treasury.gov.za/COVID19/Documents/STATS%20SA%20-%20Annexure%20B%20-%20Covid%2010%20PPE%20Procurement%2031%20July%202020.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by JoreVH** [comment]
[tabula-STATS SA - Annexure B - Covid 10 PPE Procurement 31 July 2020.xlsx](https://github.com/South-Africa-Government-Procurement/Data-cleaning/files/5314080/tabula-STATS.SA.-.Annexure.B.-.Covid.10.PPE.Procurement.31.July.2020.xlsx)

**Comment by carlvdm** [comment]
May I grab this one?

**Comment by carlvdm** [comment]
https://github.com/South-Africa-Government-Procurement/Data-cleaning/pull/182 :slightly_smiling_face:

**Comment by tristynferreiro** [comment]
Uploaded!
