### ISSUE TITLE
The Presidency - Brand South Africa pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#53]
Public Entity

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/BRAND%20SA%20-%20Report%20on%20covid%20expenditure.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201125191500/http://ocpo.treasury.gov.za/COVID19/Documents/BRAND%20SA%20-%20Report%20on%20covid%20expenditure.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by capesean** [comment]
Hey! Can I get this one?

**Comment by schalkventer** [comment]
Go for it @capesean

**Comment by schalkventer** [comment]
cap

**Comment by schalkventer** [comment]
Good work! Thanks @capesean!

**Comment by tristynferreiro** [comment]
uploaded table 1

**Comment by tristynferreiro** [comment]
Uploaded tbl 2

**Comment by tristynferreiro** [comment]
Uploaded tbl 3

**Comment by tristynferreiro** [comment]
uploaded tbl 4
