### ISSUE TITLE
Department of Cooperative Governance (DCoG) -  pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#55]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/COOPERATIVE%20GOVERNANCE%20-%20Preliminary%20Assessment%20Report%20on%20procurement%20of%20personal%20protective%20equipment.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201126193417/http://ocpo.treasury.gov.za/COVID19/Documents/COOPERATIVE%20GOVERNANCE%20-%20Preliminary%20Assessment%20Report%20on%20procurement%20of%20personal%20protective%20equipment.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by schalkventer** [comment]
Hey. Is it OK if I take this one?

**Comment by jbothma** [comment]
Please do!

**Comment by jbothma** [comment]
shouldn't we merge this?

**Comment by tristynferreiro** [comment]
uploaded
