### ISSUE TITLE
Department of Cooperative Governance (DCoG) - Municipal Infrastructure Support Agent (MISA) pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#56]
Public Entity

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/MISA%20Accounting%20Officer%27s%20Report_PPE%20Procurement%2007%20Aug%202020.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by schalkventer-demo** [comment]
Can I take this one?

**Comment by jbothma** [comment]
![Uploading Screenshot_2020-11-02_18-01-15.png…]()

**Comment by tristynferreiro** [comment]
Uploaded!
