### ISSUE TITLE
Department of International Relations and Cooperation (DIRCO) -  pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#57]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/DIRCO%20-%20Information%20related%20to%20quotations%20for%20COVID-19%20procurement%20-%20with%20explanatory%20notes.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201126195235/http://ocpo.treasury.gov.za/COVID19/Documents/DIRCO%20-%20Information%20related%20to%20quotations%20for%20COVID-19%20procurement%20-%20with%20explanatory%20notes.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by douglas86** [comment]
hey, can i take this one.

**Comment by tristynferreiro** [comment]
Uploaded
