### ISSUE TITLE
Department of Public Works and Infrastructure (DPWI) -  pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#58]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/PUBLIC%20WORKS%20AND%20INFRASTRUCTURE%20-%20Information%20regarding%20suppliers%20and%20amounts%20related%20to%20COVID19.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201102181210/http://ocpo.treasury.gov.za/COVID19/Documents/PUBLIC%20WORKS%20AND%20INFRASTRUCTURE%20-%20Information%20regarding%20suppliers%20and%20amounts%20related%20to%20COVID19.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by Chantevdw** [comment]
Can I take this one

**Comment by tristynferreiro** [comment]
Uploaded!
