### ISSUE TITLE
Department of Traditional Affairs (DTA) -  pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#59]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/TRADITIONAL%20AFFAIRS%20-%20Report%20on%20PPE%20Spending%207%20August%202020.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by Baadier-Sydow** [comment]
@jbothma can i pick this one up?

**Comment by schalkventer** [comment]
@Baadier-Sydow all yours!

**Comment by tristynferreiro** [comment]
Uploaded
