### ISSUE TITLE
Department of Correctional Services (DCS) -  pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#60]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/CORRECTIONAL%20SERVICES%20-%20SCHEDULE%20OF%20PROCUREMENT%20TO%20COMBAT%20COVID19%20-%2001%20MARCH%202020%20-%2031%20JULY%202020.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by douglas86** [comment]
Hey, can i take this one.

**Comment by tristynferreiro** [comment]
Uploaded KZN

**Comment by tristynferreiro** [comment]
Uploaded Head Office

**Comment by tristynferreiro** [comment]
Uploaded Western Cape

**Comment by tristynferreiro** [comment]
uploaded Gauteng

**Comment by tristynferreiro** [comment]
Upload EC

**Comment by tristynferreiro** [comment]
Uploaded
