### ISSUE TITLE
Department of Defence (DoD) -  pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#61]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/DEFENCE%20-%20COVID%20EXPENDITURE.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201113150652/http://ocpo.treasury.gov.za/COVID19/Documents/DEFENCE%20-%20COVID%20EXPENDITURE.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by joshramsbottom** [comment]
Hello! May I take this one?

**Comment by schalkventer** [comment]
Go for it @joshramsbottom

**Comment by tristynferreiro** [comment]
Uploaded
