### ISSUE TITLE
Department of Home Affairs (DHA) -  pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#62]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/HOME%20AFFAIRS%20-%20COVID%20SUMMARY.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by zoidyzoidzoid** [comment]
I'll do this one. 👋

**Comment by zoidyzoidzoid** [comment]
I tried to do this one, and Tesseract 4 didn't manage to OCR it well.

I'll come back to it, but someone else can feel free to grab it and have a try in the mean time.

**Comment by tristynferreiro** [comment]
Uploaded
