### ISSUE TITLE
Department of Home Affairs (DHA) -  pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#63]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/HOME%20AFFAIRS%20-%20DETAIL%20COVID%2019%20PROCUREMENT.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by rmaclean** [comment]
I'll try this one

**Comment by jbothma** [comment]
Sorry about the delay!

Looks like a bit of hidden text from the first column ended up in the supplier name column. It turns out truncated cells saved as PDF sometimes still ends up in the PDF an then makes a mess of the extraction like this. Do you mind fixing?

![Screenshot_2020-10-26_18-29-46](https://user-images.githubusercontent.com/235801/97199942-46413800-17b9-11eb-94cb-b1f0969339c8.png)
![Screenshot_2020-10-26_18-30-30](https://user-images.githubusercontent.com/235801/97199975-50fbcd00-17b9-11eb-854f-18e7fc6967d9.png)

**Comment by tristynferreiro** [comment]
Uploaded
