### ISSUE TITLE
Department of Justice and Constitutional Development (DoJ&CD) - National Prosecuting Authority of South Africa (NPA) pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#68]
Judicial Institution

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/NATIONAL%20PROSECUTING%20AUTHORITY_PPE%20-%201%20Apr%202020%20to%2031%20March%202021%20-%20Finalized%20as%20at%2007-08-2020.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by douglas86** [comment]
Hey, can i take this one.

**Comment by tristynferreiro** [comment]
Uploaded :D
