### ISSUE TITLE
Department of Justice and Constitutional Development (DoJ&CD) - Legal Aid South Africa pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#69]
Public Entity

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/Legal%20Aid%20SA%20-%20COVID%20EXPENDITURE%2007.08.2020.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by carlvdm** [comment]
Hi! :wave:
May I grab this one please? :slightly_smiling_face:

**Comment by carlvdm** [comment]
https://github.com/South-Africa-Government-Procurement/Data-cleaning/pull/172 :slightly_smiling_face:

**Comment by schalkventer** [comment]
Go for it @carlvdm!

**Comment by tristynferreiro** [comment]
Uploading

**Comment by tristynferreiro** [comment]
Uploaded *pops champagne*
