### ISSUE TITLE
FREE STATE Agriculture and Rural Development pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#7]
- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/FREE%20STATE%20AGRICULTURE%20AND%20RURAL%20DEVELOPMENT.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by CamGreen** [comment]
Hi, I am happy to take this one! Thanks.

**Comment by jbothma** [comment]
This is now on https://keepthereceipts.org.za/?implementation_location_province=Free+State
