### ISSUE TITLE
Department of Justice and Constitutional Development (DoJ&CD) - Special Investigating Unit (SIU) pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#70]
Public Entity

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/SIU%20-%20Response%20to%20Parliamentary%20question%20on%20Covid%20and%20PPE%27s%20Aug%202020.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201113002553/http://ocpo.treasury.gov.za/COVID19/Documents/SIU%20-%20Response%20to%20Parliamentary%20question%20on%20Covid%20and%20PPE%27s%20Aug%202020.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by schalkventer-demo** [comment]
Can I take this one?

**Comment by tristynferreiro** [comment]
Uploaded PPE

**Comment by tristynferreiro** [comment]
uploaded PPE other
