### ISSUE TITLE
South African Police Service (SAPS) -  pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#71]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/SAPS%20-%20PPE%20PROCUREMENT%20%28DETAILS%29.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201003092743/http://ocpo.treasury.gov.za/COVID19/Documents/SAPS%20-%20PPE%20PROCUREMENT%20%28DETAILS%29.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by zoidyzoidzoid** [comment]
I'll do this one. 👋

**Comment by jbothma** [comment]
Thanks!

**Comment by tristynferreiro** [comment]
Uploaded
