### ISSUE TITLE
South African Police Service (SAPS) -  pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#72]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/SAPS%20-%20PPE%20PROCUREMENT.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by rmaclean** [comment]
I'll grab this one

**Comment by rmaclean** [comment]
There are no tables in this document :/ 
Looks like a statement, don't think there is anything to do with it

**Comment by schalkventer** [comment]
@jbothma Happy if I close this one?

**Comment by jbothma** [comment]
Agreed - Looks like a cover letter

![Screenshot_2020-10-03_14-36-15](https://user-images.githubusercontent.com/235801/94991823-d1962780-0585-11eb-81d0-43fc1fdb2a46.png)
