### ISSUE TITLE
South African Police Service (SAPS) - Civilian Secretariat for Police Service (CSPS) pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#73]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/CSPS%20-%20PPE%20PROCUREMENT.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201109102943/http://ocpo.treasury.gov.za/COVID19/Documents/CSPS%20-%20PPE%20PROCUREMENT.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by rmaclean** [comment]
I'll grab this one

**Comment by tristynferreiro** [comment]
Uploaded!
