### ISSUE TITLE
South African Police Service (SAPS) - Independent Police Investigative Directorate (IPID) pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#74]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/IPID%20-%20PPE%20PROCUREMENT.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by douglas86** [comment]
hey, i will take this one

**Comment by tristynferreiro** [comment]
uploaded!
