### ISSUE TITLE
South African Police Service (SAPS) - Private Security Industry Regulatory Authority (PSIRA) pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#75]
Public Entity

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/PSIRA%20-%20PPE%20PROCUREMENT.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201105004830/http://ocpo.treasury.gov.za/COVID19/Documents/PSIRA%20-%20PPE%20PROCUREMENT.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by CamGreen** [comment]
Happy to take this one, thanks!

**Comment by tristynferreiro** [comment]
Uploaded goods and services

**Comment by tristynferreiro** [comment]
Uploaded decontamination
