### ISSUE TITLE
State Security Agency (SSA) -  pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#76]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/SSA%20-%20COVID19%20PPE%20Procurement%20Status%20Report%20with%20receipt%20dates.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201107183924/http://ocpo.treasury.gov.za/COVID19/Documents/SSA%20-%20COVID19%20PPE%20Procurement%20Status%20Report%20with%20receipt%20dates.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by CamGreen** [comment]
Hey, will take this one. Thanks.

**Comment by schalkventer** [comment]
Go for it!

**Comment by tristynferreiro** [comment]
Uploaded
