### ISSUE TITLE
Department of Public Enterprises (DPE) -  pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#77]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/PUBLIC%20ENTERPRISES%20-%2011082020%20Covid19%20Expenditure%20Report.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201104224348/http://ocpo.treasury.gov.za/COVID19/Documents/PUBLIC%20ENTERPRISES%20-%2011082020%20Covid19%20Expenditure%20Report.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by georgezee** [comment]
I'll take this one.
