### ISSUE TITLE
Department of Public Service and Administration (DPSA) - National School of Government (NSG) pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#78]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/NATIONAL%20SCHOOL%20OF%20GOVERNMENT%28NSG%29%20-%20COVID-19%20PPE%20PROCUREMENT.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201202134217/http://ocpo.treasury.gov.za/COVID19/Documents/NATIONAL%20SCHOOL%20OF%20GOVERNMENT%28NSG%29%20-%20COVID-19%20PPE%20PROCUREMENT.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by georgezee** [comment]
@jbothma - this is the first one I found - ok for me to take this one?

**Comment by jbothma** [comment]
Please do!

**Comment by tristynferreiro** [comment]
uploaded
