### ISSUE TITLE
Department of Public Service and Administration (DPSA) - Centre for Public Service Innovation (CPSI) pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#79]
Public Entity

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/CENTRE%20FOR%20PUBLIC%20SERVICE%20INNOVATION%20%28CPSI%29%20-%20Covid19%20expenditure%20August%202020.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by tristynferreiro** [comment]
I'll take this one!

**Comment by tristynferreiro** [comment]
Uploaded!
