### ISSUE TITLE
FREE STATE Cooperative Governance and Traditional Affairs pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#8]
- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/FREE%20STATE%20COGTA.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by NicolaasJKotze** [comment]
I will do this one.

**Comment by jbothma** [comment]
Thanks!

**Comment by jbothma** [comment]
Thanks, this is now live at https://keepthereceipts.org.za/?implementation_location_province=Free+State&buyer_name=Free+State+Department+of+Cooperative+Governance+and+Traditional+Affairs
