### ISSUE TITLE
National Treasury -  pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#80]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/NATIONAL%20TREASURY%20-%20Procurement%20during%20the%20period%20of%20the%20COVID-19%20pandemic.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201105205825/http://ocpo.treasury.gov.za/COVID19/Documents/NATIONAL%20TREASURY%20-%20Procurement%20during%20the%20period%20of%20the%20COVID-19%20pandemic.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by vrautenbach** [comment]
Hi, can you please assign this one to me. Thanks!

**Comment by tristynferreiro** [comment]
Uploaded!
