### ISSUE TITLE
National Treasury -  pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#81]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/NATIONAL%20TREASURY%20ENTITIES%20-%20Report%20on%20COVID-19%20spending.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201204141213/http://ocpo.treasury.gov.za/COVID19/Documents/NATIONAL%20TREASURY%20ENTITIES%20-%20Report%20on%20COVID-19%20spending.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by douglas86** [comment]
Hey, can i take this one.

**Comment by tristynferreiro** [comment]
Uploaded
