### ISSUE TITLE
Department of Agriculture, Land Reform and Rural Development (DALRRD) -  pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#82]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/AGRICULTURE%2c%20LAND%20REFORM%20AND%20RURAL%20DEVELOPMENT%20-%20DETAIL%20PROCUREMENT%20REPORT%20COVID19.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by zoidyzoidzoid** [comment]
I'll do this one. 👋

**Comment by jbothma** [comment]
Thanks!

**Comment by tristynferreiro** [comment]
Uploaded
