### ISSUE TITLE
Department of Agriculture, Land Reform and Rural Development (DALRRD) - Agricultural Research Council (ARC) pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#84]
Public Entity

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/ARC%20-%20Procurement%20of%20PPEs%20Report%2007.08.2020.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201202175846/http://ocpo.treasury.gov.za/COVID19/Documents/ARC%20-%20Procurement%20of%20PPEs%20Report%2007.08.2020.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by vrautenbach** [comment]
Hi, can you please assign this one to me. Thanks!

**Comment by schalkventer** [comment]
Go for it @vrautenbach!

**Comment by vrautenbach** [comment]
@schalkventer @jbothma Sorry, I am struggling with this one. I have done OCR, but not getting some of the rows out. For example the amounts are completely cut off.

**Comment by tristynferreiro** [comment]
[Uploading ARC - Procurement of PPEs Report 07.08.2020 - OCR.pdf…]()

**Comment by tristynferreiro** [comment]
Uploaded
