### ISSUE TITLE
Department of Agriculture, Land Reform and Rural Development (DALRRD) - National Agricultural Marketing Council (NAMC) pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#85]
Public Entity

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/NAMC%20-%20Report%20Procurement%20of%20PPEs.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by martink-rsa** [comment]
I would like this, please.

**Comment by martink-rsa** [comment]
https://github.com/South-Africa-Government-Procurement/Data-cleaning/pull/120

**Comment by tristynferreiro** [comment]
Uploaded
