### ISSUE TITLE
Department of Agriculture, Land Reform and Rural Development (DALRRD) - Onderstepoort Biological Products (OBP) pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#86]
Public Entity

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/Onderstepoort%20Biological%20Products%20COVID%20Procurement%20Report.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201104233830/http://ocpo.treasury.gov.za/COVID19/Documents/Onderstepoort%20Biological%20Products%20COVID%20Procurement%20Report.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by CamGreen** [comment]
Hi, I am happy to tackle this one. Thanks

**Comment by tristynferreiro** [comment]
Uploaded!
