### ISSUE TITLE
Department of Agriculture, Land Reform and Rural Development (DALRRD) - Perishable Products Export Control Board (PPECB) pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#87]
Public Entity

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/PPECB%20-%20Response%20%28Procurement%20during%20period%20of%20COVID-19%20pandemic%29.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201128111142/http://ocpo.treasury.gov.za/COVID19/Documents/PPECB%20-%20Response%20%28Procurement%20during%20period%20of%20COVID-19%20pandemic%29.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by patbpm** [comment]
Good Day

I would like to be assigned with issues. 

I am looking forward

**Comment by jbothma** [comment]
Fantastic! Please do

JD

**Comment by tristynferreiro** [comment]
Uploaded
