### ISSUE TITLE
Department of Communications and Digital Technologies (DCDT) -  pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#88]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/COMMUNICATIONS%20AND%20DIGITAL%20TECHNOLOGY%20-%20COVID%20procurement%20spending%2018.08.2020.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201202174745/http://ocpo.treasury.gov.za/COVID19/Documents/COMMUNICATIONS%20AND%20DIGITAL%20TECHNOLOGY%20-%20COVID%20procurement%20spending%2018.08.2020.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by vrautenbach** [comment]
Hi, can you please assign this one to me. Thanks!

**Comment by schalkventer** [comment]
Go for it @vrautenbach!

**Comment by tristynferreiro** [comment]
Uploaded
