### ISSUE TITLE
Department of Communications and Digital Technologies (DCDT) - Independent Communications Authority of South Africa (ICASA) pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#89]
Constitutional Body

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/ICASA%20Annexure%20A%20-%20COVID%20Procurement%20Spending%20%28Lt%20I-Ministerial%20Committee%29.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by vrautenbach** [comment]
Hi, can you please assign this one to me. Thanks!

**Comment by tristynferreiro** [comment]
Uploaded
