### ISSUE TITLE
Department of Communications and Digital Technologies (DCDT) - Broadband Infraco pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#90]
Public Entity

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/BROADBAND%20INFRACO%20-%20Response%20Procurement%20Spending%20During%20COVID-19%20Pandemic%2020200824.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by vrautenbach** [comment]
Hi, can you please assign this one to me. Thanks!

**Comment by tristynferreiro** [comment]
uploaded
