### ISSUE TITLE
Department of Communications and Digital Technologies (DCDT) - Film and Publication Board (FPB) pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#91]
Public Entity

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/FILM%20AND%20PUBLICATION%20BOARD%20-%20Procurement%20of%20COVID-19%20Related%20Goods%20and%20Services.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201106202504/http://ocpo.treasury.gov.za/COVID19/Documents/FILM%20AND%20PUBLICATION%20BOARD%20-%20Procurement%20of%20COVID-19%20Related%20Goods%20and%20Services.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by vrautenbach** [comment]
Hi, can you please assign this one to me. Thanks!

**Comment by jbothma** [comment]
Will do, thanks!

**Comment by tristynferreiro** [comment]
Uploaded
