### ISSUE TITLE
Department of Communications and Digital Technologies (DCDT) - Sentech pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#93]
Public Entity

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/SENTECH%20SOC%20LIMITED%20-%20PPE%20SERVICE%20PROVIDERS%20AUGUST%202020.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201202191813/http://ocpo.treasury.gov.za/COVID19/Documents/SENTECH%20SOC%20LIMITED%20-%20PPE%20SERVICE%20PROVIDERS%20AUGUST%202020.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by 22xb** [comment]
Hi, I'd like to go through this file

**Comment by schalkventer** [comment]
Go for it @DK-Nkabinde

**Comment by tristynferreiro** [comment]
Uploaded
