### ISSUE TITLE
Department of Communications and Digital Technologies (DCDT) - South African Post Office (SAPO) pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#94]
Public Entity

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/SAPO%20-%20Summary%20of%20Total%20COVID%20Procurement%20Spending.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by 22xb** [comment]
Hi, I'd like to go through this file

**Comment by schalkventer** [comment]
All yours :)

**Comment by tristynferreiro** [comment]
This is just a summary
