### ISSUE TITLE
Department of Communications and Digital Technologies (DCDT) - South African Post Office (SAPO) pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#95]
Public Entity

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/SAPO%20-%20%20March%202020%20to%20August%202020%20Covid%2019%20-%20Detailed%20Spending.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by douglas86** [comment]
Hey, can I sort through this file.

**Comment by schalkventer** [comment]
Go for it @douglas86

**Comment by jbothma** [comment]
could you fill down the supplier name? Since there's an order amount for each item, we'd like a complete record (including supplier name) - for each item - but then we should fill down so that the supplier is actually tied to each item.

https://github.com/South-Africa-Government-Procurement/Data-cleaning#what-should-i-do-if-there-are-merged-cells-that-should-be-split

![Screenshot_2020-10-03_17-56-08](https://user-images.githubusercontent.com/235801/94996006-47a88780-05a2-11eb-9aa5-195f2414ff96.png)

![Screenshot_2020-10-03_18-04-21](https://user-images.githubusercontent.com/235801/94996114-e8974280-05a2-11eb-8b44-fc3f7b8b3436.png)

**Comment by tristynferreiro** [comment]
Uploaded table 1

**Comment by tristynferreiro** [comment]
Uploaded table 2
