### ISSUE TITLE
Department of Environment, Forestry and Fisheries (DEFF) -  pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#96]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/FORESTRY%2c%20FISHERIES%20AND%20ENVIRONMENT%20-%20Covid19%20Procurement%20for%202020-21%20FY%20as%20of%2007%20August%202020.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201112222222/http://ocpo.treasury.gov.za/COVID19/Documents/FORESTRY,%20FISHERIES%20AND%20ENVIRONMENT%20-%20Covid19%20Procurement%20for%202020-21%20FY%20as%20of%2007%20August%202020.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by runningdeveloper** [comment]
Can I have this one. 
This project is an awesome idea!

**Comment by jbothma** [comment]
Grab it! Thanks for joining!

Best
JD

**Comment by tristynferreiro** [comment]
Uploaded
