### ISSUE TITLE
Department of Mineral Resources and Energy (DMRE) -  pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#97]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/DMRE%20Inter-Ministerial%20Commitee%20-%20Covid%2019%20%28PPE%29%20Procurement.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by JoreVH** [comment]
Can I have this one please?

**Comment by JoreVH** [comment]
[Uploading DMRE Inter-Ministerial Commitee - Covid 19 (PPE) Procurement_ocr.pdf…]()

**Comment by schalkventer** [comment]
Go for it @JoreVH!

**Comment by tristynferreiro** [comment]
Uploaded
