### ISSUE TITLE
Department of Science and Innovation (DSI) -  pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#98]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/SCIENCE%20and%20INNOVATION%20and%20ENTITIES%20-%20COVID19%20PROCUREMENTS.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201024130844/http://ocpo.treasury.gov.za/COVID19/Documents/SCIENCE%20and%20INNOVATION%20and%20ENTITIES%20-%20COVID19%20PROCUREMENTS.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by sacheen** [comment]
could i take this one?

**Comment by jbothma** [comment]
please do!

**Comment by TeeOli** [comment]
May i take this one?

**Comment by tristynferreiro** [comment]
Uploaded!
