### ISSUE TITLE
Department of Small Business Development (DSBD) -  pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#99]
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/SMALL%20BUSINESS%20DEVELOPMENT%20and%20ENTITIES%20PORTFOLIO%20-%20RESPONSE%20Aug%2011%202020.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201204142105/http://ocpo.treasury.gov.za/COVID19/Documents/SMALL%20BUSINESS%20DEVELOPMENT%20and%20ENTITIES%20PORTFOLIO%20-%20RESPONSE%20Aug%2011%202020.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by nefiger** [comment]
mine?

**Comment by jbothma** [comment]
You'd be a star, as always. Thanks!

**Comment by tristynferreiro** [comment]
Uploaded pg 1-3

**Comment by tristynferreiro** [comment]
uploaded SEDA table

**Comment by tristynferreiro** [comment]
Uploaded
